default:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
account:
    resource: "@AppBundle/Controller/AccountController.php"
    type:     annotation
    prefix:   /account
admin:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
user_bundle:
    resource: "@UserBundle/Controller/DefaultController.php"
    type:     annotation


#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

#OAuth Callbacks
facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

twitter_login:
    path: /login/check-twitter

# Redirect login/register URLs
override_login_route:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /#login
        permanent: true
    methods:  [GET]

override_password_reset:
    path: /resetting/request
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /#login
        permanent: true
    methods:  [GET]

override_register_route:
    path: /register
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /#register
        permanent: true
    methods:  [GET]

#FOSUserBundle Routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
