# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    access_denied_url: /#login
    
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:  bcrypt
            cost:       15

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:          
            form_login:
                login_path: /#login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                failure_handler: user_bundle.authentication_handler
                success_handler: user_bundle.authentication_handler
                default_target_path: '%login_default_target%'
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/account/, role: ROLE_USER }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }

