# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.admin_manage:
    class: AppBundle\Controller\AdminController
    arguments: ["@templating", "@sonata.seo.page", "%kernel.root_dir%", "@app.admin_manage_actions", "@plupload.handler", "@app.course_manager"]

  app.admin_manage_actions:
    class: AppBundle\Controller\Actions\AdminActions
    arguments: ["@doctrine.orm.entity_manager", "@validator"]
    public: false

  app.validator.sort_value:
    class: AppBundle\Validator\Constraints\ValidateSortValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: validator.constraint_validator }

  app.course_manager:
    class: AppBundle\Course\CourseManager
    arguments: ["@security.authorization_checker", "@security.token_storage", "@doctrine.orm.entity_manager", "@app.session_manager", "@router"]
    public: true

  app.session_manager:
    class: AppBundle\Course\SessionManager
    arguments: ["@doctrine.orm.entity_manager", "@router", "@sonata.seo.page", "@session", "@templating", "@form.factory"]
    public: false

  app.session_type:
    class: AppBundle\Form\SessionType
    arguments: []
    tags:
        - { name: form.type }

  app.choice_type_extension:
    class: AppBundle\Form\Extension\ChoiceTypeExtension
    tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }

  app.text_type_extension:
    class: AppBundle\Form\Extension\TextTypeExtension
    tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

  app.number_type_extension:
    class: AppBundle\Form\Extension\NumberTypeExtension
    tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\NumberType }
  
  app.submit_type_extension:
    class: AppBundle\Form\Extension\SubmitTypeExtension
    tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\SubmitType }

  app.checkbox_type_extension:
    class: AppBundle\Form\Extension\CheckboxTypeExtension
    tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CheckboxType }

  app.validator.course_data_var:
    class: AppBundle\Validator\Constraints\CourseDataVarValidator
    arguments: ["@app.course_manager"]
    tags:
      - { name: validator.constraint_validator }

  app.course_reminder_provider:
    class: AppBundle\Course\CourseReminderProvider
    arguments: ["@mailer", "@doctrine.orm.entity_manager", "@event_dispatcher", "@templating", "%mailer_user%", "%mailer_sender_name%", "@router"]
    public: true

  app.user_settings:
    class: AppBundle\Utils\UserSettings
    arguments: ["@security.token_storage", "@doctrine.orm.entity_manager"]
    public: true

  app.markdown:
    class: AppBundle\Utils\Markdown

  app.twig.markdown_extension:
    class:     AppBundle\Twig\MarkdownExtension
    arguments: ['@app.markdown']
    public:    false
    tags:
      - { name: twig.extension }
  
  twig.extension.stringloader:
    class: Twig_Extension_StringLoader
    tags:
        - { name: twig.extension }