# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.admin_manage:
    class: AppBundle\Controller\AdminController
    arguments: ["@templating", "@sonata.seo.page", "%kernel.root_dir%", "@app.admin_manage_actions", "@plupload.handler"]

  app.admin_manage_actions:
    class: AppBundle\Utils\AdminManageActions
    arguments: ["@doctrine.orm.entity_manager", "@validator"]
    public: false

  app.validator.sort_value:
    class: AppBundle\Validator\Constraints\ValidateSortValidator
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: validator.constraint_validator }

  app.course_manager:
    class: AppBundle\Manager\CourseManager
    arguments: ["@security.authorization_checker", "@security.token_storage", "@doctrine.orm.entity_manager"]
    public: false

  app.session_manager:
    class: AppBundle\Manager\SessionManager
    arguments: ["@doctrine.orm.entity_manager", "@app.course_manager"]
    public: true