services:
    login_register:
        class: UserBundle\EventListener\LoginRegisterListener
        arguments: ["@request_stack"]
        tags:
            - { name: kernel.event_subscriber }

    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }