services:
    user_bundle.user_register_reset_password_listener:
        class: UserBundle\EventListener\UserRegisterResetPasswordListener
        arguments: ["@request_stack", "@translator", "@security.token_storage", "@session", "@router", "%fos_user.resetting.retry_ttl%", "%login_default_target%"]
        tags:
            - { name: kernel.event_subscriber }

    user_bundle.user_change_password_listener:
        class: UserBundle\EventListener\UserChangePasswordListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }

    user_bundle.authentication_handler:
        class: UserBundle\AuthenticationHandler
        arguments: ["@router", "@session", "@translator", "%login_default_target%", "%login_admin_target%"]

    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    
    user.form.change_email.factory:
        class: FOS\UserBundle\Form\Factory\FormFactory
        arguments: ["@form.factory", app_user_change_email, UserBundle\Form\ChangeEmailType, [Profile, Default]]

    user.form.change_email.type:
        class: UserBundle\Form\ChangeEmailType
        arguments: ["%fos_user.model.user.class%", "@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: app_user_change_email }

    #user_bundle.form.change_email:
    #    class: UserBundle\Form\ChangeEmailType
    #    tags:
    #        - { name: form.type, alias: user_change_email }

    #user_bundle.form.change_settings:
    #    class: UserBundle\Form\ChangeSettingsType
    #    tags:
    #        - { name: form.type, alias: user_change_settings }

    userbundle.oauth_user_provider:
        class: UserBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{facebook: facebook_id, google: google_id, twitter: twitter_id}]