services:
    user_bundle.register_listener:
        class: UserBundle\EventListener\RegisterListener
        arguments: ["@request_stack"]
        tags:
            - { name: kernel.event_subscriber }

    user_bundle.authentication_handler:
        class: UserBundle\AuthenticationHandler
        arguments: ["@router", "@session", "@translator", "%login_default_target%", "%login_admin_target%"]

    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }